application: gdrive-cms-py-gae
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: static/assets

- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: main.app
